version: "3.8"
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: trading_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - timescale_data:/var/lib/postgresql/data

volumes:
  timescale_data: